In [1]:
!pip install h5py

Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 36.8 MB/s eta 0:00:0000:0100:01
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.


In [2]:
import h5py
import scipy
import scipy.io as sio
import numpy as np

In [ ]:
# def read_hdf5(filename, dataset_name='dataset'):
#     with h5py.File(filename, 'r') as f:
#         if dataset_name in f:
#             data = f[dataset_name][:]
#         else:
#             raise KeyError(f"数据集 '{dataset_name}' 不存在")
#     return data

# # 读取数据
# filename = '../data/dataset01/100%_demo_1.h5'
# try:
#     data = read_hdf5(filename)
#     print(f"读取的数据: {data}")
# except KeyError as e:
#     print(e)

In [12]:
def h5_to_mat(h5_file_path, mat_file_path):
    """
    将 HDF5 文件转换为 MATLAB 文件
    :param h5_file_path: HDF5 文件的路径
    :param mat_file_path: MATLAB 文件的保存路径
    """
    try:
        # 打开 HDF5 文件
        with h5py.File(h5_file_path, 'r') as h5_file:
            # 创建一个空字典，用于存储 HDF5 文件中的数据
            data_dict = {}
            # 遍历 HDF5 文件中的所有数据集
            for key in h5_file.keys():
                data = np.squeeze(h5_file[key][:])
                # 将数据集的数据存储到字典中
                data_dict[key] = data
                print(data, len(data))

        # 将字典中的数据保存为 MATLAB 文件
        sio.savemat(mat_file_path, data_dict)
        print(f"成功将 {h5_file_path} 转换为 {mat_file_path}")
    except Exception as e:
        print(f"转换过程中出现错误: {e}")

# 示例用法
# h5_file_path = 'your_file.h5'
# mat_file_path = 'your_file.mat'
# h5_to_mat(h5_file_path, mat_file_path)

In [40]:
# h5_to_mat('../data/dataset01/10_1.h5', '../data/dataset01/10_1.mat')
# h5_to_mat('../data/dataset01/10_2_0.h5', '../data/dataset01/10_2_0.mat')
# h5_to_mat('../data/dataset01/10_2_90.h5', '../data/dataset01/10_2_180.mat')
# h5_to_mat('../data/dataset01/10_2_180.h5', '../data/dataset01/10_2_90.mat')
# h5_to_mat('../data/dataset01/10_3.h5', '../data/dataset01/10_3.mat')
# h5_to_mat('../data/dataset01/10_0.h5', '../data/dataset01/10_0.mat')

[ 5.214724  3.98773   3.98773  ... 11.96319   5.521472 23.619633]
成功将 ../data/dataset01/10_1.h5 转换为 ../data/dataset01/10_1.mat
[34.969322  2.147239 12.269938 ...  1.840491  8.282208 14.417178]
成功将 ../data/dataset01/10_2_0.h5 转换为 ../data/dataset01/10_2_0.mat
[ 0.306748  1.840491  0.920245 ...  9.202454 15.95092   4.907975]
成功将 ../data/dataset01/10_2_90.h5 转换为 ../data/dataset01/10_2_180.mat
[28.527607  4.294478 64.723923 ... 26.07362   6.441718 24.846626]
成功将 ../data/dataset01/10_2_180.h5 转换为 ../data/dataset01/10_2_90.mat
[2.453988 7.055215 9.509203 ... 0.613497 1.533742 2.453988]
成功将 ../data/dataset01/10_3.h5 转换为 ../data/dataset01/10_3.mat
[1.226994 0.306748 4.294478 ... 3.680981 2.147239 8.588957]
成功将 ../data/dataset01/10_0.h5 转换为 ../data/dataset01/10_0.mat


In [20]:
h5_to_mat('../data/try/try05.h5', '../data/try/try.mat')

[-0.306748 -0.306748  0.306748 ... -0.306748  0.613497  0.306748] 10240
成功将 ../data/try/try05.h5 转换为 ../data/try/try.mat


In [25]:
h5_to_mat('../data/pre03/old_100_0_4.23.h5', '../data/pre03/old_100_0.mat')

[-11.349693   1.533742  -3.067485 ...   7.055215  -2.147239  -8.588957] 102400
成功将 ../data/pre03/old_100_0_4.23.h5 转换为 ../data/pre03/old_100_0.mat


In [22]:
h5_to_mat('../data/dataset03/200_0_4.23.h5', '../data/dataset03/200_0.mat')
h5_to_mat('../data/dataset03/100_1_4.23.h5', '../data/dataset03/100_1.mat')
h5_to_mat('../data/dataset03/100_2_0_4.23.h5', '../data/dataset03/100_2_0.mat')
h5_to_mat('../data/dataset03/100_2_90_4.23.h5', '../data/dataset03/100_2_90.mat')
h5_to_mat('../data/dataset03/100_2_180_4.23.h5', '../data/dataset03/100_2_180.mat')
h5_to_mat('../data/dataset03/100_3_4.23.h5', '../data/dataset03/100_3.mat')
h5_to_mat('../data/dataset03/old_200_0_4.23.h5', '../data/dataset03/old_200_0.mat')
# h5_to_mat('../data/origin_200_0.h5', '../data/CWRU_dataset02/drive_200_0.mat')
# h5_to_mat('../data/old_200_0.h5', '../data/CWRU_dataset02/old_200_0.mat')

[-28.22086    3.067485  11.349693 ...   8.588957   3.067485  -2.760736] 204800
成功将 ../data/dataset03/200_0_4.23.h5 转换为 ../data/dataset03/200_0.mat
[-192.024536  457.055237 -167.484665 ... -225.153366   20.858896
 -199.079742] 102400
成功将 ../data/dataset03/100_1_4.23.h5 转换为 ../data/dataset03/100_1.mat
[ 17.177914  12.883435 -12.883435 ...  17.79141   40.184048 -44.785275] 102400
成功将 ../data/dataset03/100_2_0_4.23.h5 转换为 ../data/dataset03/100_2_0.mat
[ 3.680981  7.97546  -0.306748 ...  2.453988  2.760736 -1.533742] 102400
成功将 ../data/dataset03/100_2_90_4.23.h5 转换为 ../data/dataset03/100_2_90.mat
[ -3.067485 -38.650307  10.736197 ... -58.895702 -12.883435  11.96319 ] 102400
成功将 ../data/dataset03/100_2_180_4.23.h5 转换为 ../data/dataset03/100_2_180.mat
[-0.306748  3.98773  -3.374233 ...  7.361963  9.509203  6.748466] 102400
成功将 ../data/dataset03/100_3_4.23.h5 转换为 ../data/dataset03/100_3.mat
[ -7.055215 -15.644171   2.760736 ...   4.294478  -6.134969   1.840491] 204800
成功将 ../data/dataset03/old_

In [13]:
mat_data = scipy.io.loadmat('../data/dataset02/200_0.mat')
mat_data

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Tue Apr 22 10:57:30 2025',
 '__version__': '1.0',
 '__globals__': [],
 'dataset': array([[ 7.361963,  2.453988,  9.509203, ..., 16.871166,  2.453988,
          1.226994]])}